fritter: clean
	@echo ###### Building gen_poly ######
	cl /nologo tools\gen_poly.c -Fe:gen_poly.exe
	.\gen_poly.exe include\poly_seed.h

	@echo ###### Building gen_api_shuffle ######
	cl /nologo tools\gen_api_shuffle.c -Fe:gen_api_shuffle.exe
	.\gen_api_shuffle.exe include\api_master.h include\api_shuffle.h

	@echo ###### Building exe2h ######
	cl /nologo loader\exe2h\exe2h.c loader\exe2h\mmap-windows.c

	@echo ###### Building loader (PEB order 1) ######
	cl /std:clatest /utf-8 -Zp8 -c -nologo -Gy -Os -O1 -GR- -EHa -Oi -GS- -DPEB_WALK_ORDER=1 -I include loader\loader.c hash.c encrypt.c loader\depack.c loader\clib.c
	link -nologo -entry:FritterLoader -fixed -subsystem:console -nodefaultlib -out:loader_peb1.exe loader.obj hash.obj encrypt.obj depack.obj clib.obj
	.\exe2h.exe loader_peb1.exe

	@echo ###### Building loader (PEB order 2) ######
	cl /std:clatest /utf-8 -Zp8 -c -nologo -Gy -Os -O1 -GR- -EHa -Oi -GS- -DPEB_WALK_ORDER=2 -I include loader\loader.c hash.c encrypt.c loader\depack.c loader\clib.c
	link -nologo -entry:FritterLoader -fixed -subsystem:console -nodefaultlib -out:loader_peb2.exe loader.obj hash.obj encrypt.obj depack.obj clib.obj
	.\exe2h.exe loader_peb2.exe

	@echo ###### Building dispatch shim ######
	cl /std:clatest /utf-8 -Zp8 -c -nologo -Gy -Os -O1 -GR- -EHa -Oi -GS- -I include loader\dispatch_shim.c
	link -nologo -entry:DispatchShimEntry -fixed -subsystem:console -nodefaultlib -out:dispatch_shim.exe dispatch_shim.obj
	.\exe2h.exe dispatch_shim.exe

	@echo ###### Building generator ######
	cl /std:clatest /utf-8 -Zp8 -DFRITTER_EXE -I include fritter.c hash.c encrypt.c format.c loader\clib.c lib\aplib64.lib -Fe:fritter.exe
	cl /std:clatest /utf-8 -Zp8 -nologo -DDLL -LD -I include fritter.c hash.c encrypt.c format.c loader\clib.c lib\aplib64.lib -Fe:fritter.dll
	move fritter.lib lib\fritter.lib
	move fritter.exp lib\fritter.exp
	move fritter.dll lib\fritter.dll

debug: clean
	cl /nologo tools\gen_poly.c -Fe:gen_poly.exe
	.\gen_poly.exe include\poly_seed.h

	cl /nologo tools\gen_api_shuffle.c -Fe:gen_api_shuffle.exe
	.\gen_api_shuffle.exe include\api_master.h include\api_shuffle.h

	cl /nologo loader\exe2h\exe2h.c loader\exe2h\mmap-windows.c

	cl /std:clatest /utf-8 -Zp8 -c -nologo -Gy -Os -O1 -GR- -EHa -Oi -GS- -DPEB_WALK_ORDER=1 -I include loader\loader.c hash.c encrypt.c loader\depack.c loader\clib.c
	link -nologo -entry:FritterLoader -fixed -subsystem:console -nodefaultlib -out:loader_peb1.exe loader.obj hash.obj encrypt.obj depack.obj clib.obj
	.\exe2h.exe loader_peb1.exe

	cl /std:clatest /utf-8 -Zp8 -c -nologo -Gy -Os -O1 -GR- -EHa -Oi -GS- -DPEB_WALK_ORDER=2 -I include loader\loader.c hash.c encrypt.c loader\depack.c loader\clib.c
	link -nologo -entry:FritterLoader -fixed -subsystem:console -nodefaultlib -out:loader_peb2.exe loader.obj hash.obj encrypt.obj depack.obj clib.obj
	.\exe2h.exe loader_peb2.exe

	cl /std:clatest /utf-8 -Zp8 -c -nologo -Gy -Os -O1 -GR- -EHa -Oi -GS- -I include loader\dispatch_shim.c
	link -nologo -entry:DispatchShimEntry -fixed -subsystem:console -nodefaultlib -out:dispatch_shim.exe dispatch_shim.obj
	.\exe2h.exe dispatch_shim.exe

	cl /std:clatest /utf-8 -Zp8 -nologo -DDEBUG -c -nologo -Gy -Os -EHa -GS- -I include loader\loader.c hash.c encrypt.c loader\depack.c loader\clib.c
	link -nologo -subsystem:console loader.obj hash.obj encrypt.obj depack.obj clib.obj

	cl /std:clatest /utf-8 -Zp8 -nologo -DDEBUG -DFRITTER_EXE -I include fritter.c hash.c encrypt.c format.c loader\clib.c lib\aplib64.lib -Fe:fritter.exe
	cl /std:clatest /utf-8 -Zp8 -nologo -DDEBUG -DDLL -LD -I include fritter.c hash.c encrypt.c format.c loader\clib.c lib\aplib64.lib -Fe:fritter.dll
	move fritter.lib lib\fritter.lib
	move fritter.exp lib\fritter.exp
	move fritter.dll lib\fritter.dll

hash:
	cl -Zp8 -nologo -DTEST -I include hash.c loader\clib.c
encrypt:
	cl -Zp8 -nologo -DTEST -I include encrypt.c

# Test harness. Built into test\ where tools\seed_sweep.py expects it.
# Not part of `fritter` or `clean`, these are committed fixtures, so a plain
# build never dirties them; run this target only to rebuild them deliberately.
harness:
	@echo ###### Building test harness ######
	cl /nologo /utf-8 loader\inject_local.c -Fe:test\inject_local64.exe
	cl /nologo /utf-8 loader\inject.c -Fe:test\inject64.exe
clean:
	@del /Q mmap-windows.obj fritter.obj hash.obj encrypt.obj depack.obj format.obj clib.obj veh_shim.obj dispatch_shim.obj inject.obj inject_local.obj gen_poly.obj gen_poly.exe gen_api_shuffle.obj gen_api_shuffle.exe include\poly_seed.h include\api_shuffle.h exe2h.exe loader.exe loader_peb1.exe loader_peb2.exe loader_peb1_exe_x64.h loader_peb2_exe_x64.h loader_peb1_fn_table_x64.h loader_peb1_ref_table_x64.h loader_peb2_fn_table_x64.h loader_peb2_ref_table_x64.h veh_shim.exe veh_shim_exe_x64.h dispatch_shim.exe dispatch_shim_exe_x64.h dispatch_shim_fn_table_x64.h dispatch_shim_ref_table_x64.h hash.exe encrypt.exe fritter.exe lib\fritter.lib lib\fritter.exp lib\fritter.dll 2>nul
