/*
 * gen_api_shuffle - reads include/api_master.h, shuffles its XAPI
 * lines (slot 0 pinned), writes include/api_shuffle.h.
 *
 * fritter.h and fritter.c both #include "api_shuffle.h" with their
 * own XAPI macro definition, so the typed-struct layout and the
 * api_imports[] table cannot disagree by construction.
 *
 * Seeding: same FRITTER_BUILD_SEED env var as gen_poly. The seed is
 * mixed once before use so the api shuffle does not lock-step with
 * the cipher/hash constants - same seed reproduces both, but they
 * vary independently as the seed changes.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <stdint.h>

#define MAX_LINES    256
#define MAX_LINE_LEN 1024

static uint32_t xorshift32(uint32_t *s) {
    uint32_t x = *s;
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    return *s = x;
}

int main(int argc, char **argv) {
    const char *master_path = (argc > 1) ? argv[1] : "include/api_master.h";
    const char *out_path    = (argc > 2) ? argv[2] : "include/api_shuffle.h";

    FILE *f = fopen(master_path, "r");
    if (!f) { fprintf(stderr, "gen_api_shuffle: cannot open %s\n", master_path); return 1; }

    char *lines[MAX_LINES] = {0};
    int n = 0;
    char buf[MAX_LINE_LEN];
    while (fgets(buf, sizeof(buf), f)) {
        const char *p = buf;
        while (*p == ' ' || *p == '\t') p++;
        if (strncmp(p, "XAPI(", 5) != 0) continue;
        if (n >= MAX_LINES) {
            fprintf(stderr, "gen_api_shuffle: too many XAPI lines (max %d)\n", MAX_LINES);
            return 1;
        }
        size_t len = strlen(buf);
        char *copy = (char *)malloc(len + 1);
        if (!copy) { fprintf(stderr, "gen_api_shuffle: oom\n"); return 1; }
        memcpy(copy, buf, len + 1);
        lines[n++] = copy;
    }
    fclose(f);
    if (n == 0) { fprintf(stderr, "gen_api_shuffle: no XAPI lines in %s\n", master_path); return 1; }

    uint32_t seed;
    const char *env = getenv("FRITTER_BUILD_SEED");
    if (env && *env) {
        seed = (uint32_t)strtoul(env, NULL, 0);
    } else {
        uintptr_t mix = (uintptr_t)&seed;
        seed = (uint32_t)(time(NULL) ^ (mix >> 3) ^ (mix << 11));
    }
    if (seed == 0) seed = 0x5A5A5A5Au;

    /* Mix once so api shuffle does not lock-step with gen_poly's stream */
    uint32_t s = seed ^ 0xDEADBEEFu;
    (void)xorshift32(&s);

    /* Fisher-Yates over indices [1, n-1]. Slot 0 stays as LoadLibraryA. */
    int idx[MAX_LINES];
    for (int i = 0; i < n; i++) idx[i] = i;
    for (int i = n - 1; i >= 2; i--) {
        int j = 1 + (int)(xorshift32(&s) % (uint32_t)i);  /* j in [1, i] */
        int t = idx[i]; idx[i] = idx[j]; idx[j] = t;
    }

    FILE *o = fopen(out_path, "w");
    if (!o) { fprintf(stderr, "gen_api_shuffle: cannot open %s for writing\n", out_path); return 1; }
    fprintf(o, "/* Auto-generated by tools/gen_api_shuffle. Do not edit. */\n");
    fprintf(o, "/* Build seed: 0x%08X - slot 0 pinned as LoadLibraryA */\n", seed);
    for (int i = 0; i < n; i++) fputs(lines[idx[i]], o);
    fclose(o);

    fprintf(stderr, "[api_shuffle] %s seed=0x%08X (%d entries, slot 0 pinned)\n",
            out_path, seed, n);
    return 0;
}
